import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "public/styles/globals.css";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Error",
  description: "Generated by create next app",
};

export default function ErrorLayout({
  children,
}: Readonly<{
  children: [React.ReactNode];
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="w-full flex justify-center">{children}</div>
      </body>
    </html>
  );
}
