/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 scene.gltf --transform 
Files: scene.gltf [4.19KB] > E:\Workspace\Next\nextFE\public\models\scene-transformed.glb [533.2KB] (-12626%)
Author: martinjario (https://sketchfab.com/martinjario)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/skull-downloadable-1a9db900738d44298b0bc59f68123393
Title: Skull downloadable
*/

import React from "react";
import { useGLTF } from "@react-three/drei";
import { Canvas } from "@react-three/fiber";
export function Skull(props: any) {
  const { nodes, materials } = useGLTF("../../../public/models/skull.glb");
  return (
    <Canvas>
      <group {...props} dispose={null}>
        <mesh
          //@ts-ignore
          geometry={nodes.Object_2.geometry}
          material={materials.defaultMat}
          rotation={[-Math.PI / 2, 0, 0]}
        />
      </group>
    </Canvas>
  );
}

useGLTF.preload("../../../public/models/skull.glb");
