export const playlist = [
  [
    "1_Tango Alpha Bravo.ogg",
    "2_Polyester Jammy.ogg",
    "3_Hyman's Wrath.ogg",
    "4_Slow and Spacious.ogg",
    "5_Mean.ogg",
    "6_Medieval Melody.ogg",
    "7_Sh'washa.ogg",
    "8_Crawly.ogg",
    "9_Fretless Salsa.ogg",
    "10_Bigelow's Bungalow.ogg",
  ],
  [
    "1_Tango Alpha Bravo_DE.flac",
    "2_Polyester Jammy_DE.flac",
    "3_Hyman's Wrath_DE.flac",
    "4_Slow and Spacious_DE.flac",
    "5_Mean_DE.flac",
    "6_Medieval Melody_DE.flac",
    "7_Sh'washa_DE.flac",
    "8_Crawly_DE.flac",
    "9_Fretless Salsa_DE.flac",
    "10_Bigelow's Bungalow_DE.flac",
  ],
];
