import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Header from "./components/header";
import Footer from "./components/footer";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "HHUUYYLLEE",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: [React.ReactNode];
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="">
          <Header />
        </div>
        {children}
        <div className="bg-gray-800">
          <Footer />
        </div>
      </body>
    </html>
  );
}
