import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "public/styles/globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "HHUUYYLLEE",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: [React.ReactNode];
}>) {
  return (
    <html lang="en">
      <body className={inter.className + " bg-[#12101b] "}>{children}</body>
    </html>
  );
}
